name: Synopsys Action - Black Duck

on:
  workflow_dispatch

jobs:
  Synopsys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2        
    - name: Restore
      run: dotnet restore
              
    - name: Black Duck Scan (SCA)
      uses: synopsys-sig/synopsys-action@v1.1.0
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
      with:
        blackduck_url: ${{ secrets.BD_URL }}
        blackduck_apiToken: ${{ secrets.BD_TOKEN }}
        blackduck_automation_fixpr: false
