name: "Coverity On Premises"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      COVERITY_OS: "linux64"
      COVERITY_URL:  ${{ secrets.COVERITY_URL }}
      COVERITY_USER:  ${{ secrets.COVERITY_USER  }}
      COVERITY_CLI_CONNECT_USERNAME: ${{ secrets.COVERITY_USER  }}
      COVERITY_CLI_CONNECT_PASSWORD: ${{ secrets.COVERITY_PASSWORD  }}
      COVERITY_PASSWORD: ${{ secrets.COVERITY_PASSWORD  }}
      COVERITY_VERSION: ${{ secrets.COVERITY_VERSION  }}

    steps:
    - uses: actions/checkout@v2        
    - name: Restore
      run: dotnet restore
      
    - name: Download Coverity
      run: |        
          curl -fLsS --user $COVERITY_USER:$COVERITY_PASSWORD $COVERITY_URL/downloadFile.htm?fn=cov-analysis-$COVERITY_OS-$COVERITY_VERSION.tar.gz | tar -C /tmp -xzf -
          curl -fLsS --user $COVERITY_USER:$COVERITY_PASSWORD -o /tmp/cov-analysis-$COVERITY_OS-$COVERITY_VERSION/bin/license.dat $COVERITY_URL/downloadFile.htm?fn=license-cov-unlocked.dat
          echo "/tmp/cov-analysis-$COVERITY_OS-$COVERITY_VERSION/bin/" >> $GITHUB_PATH
  
    - name: Coverity Scan
      run: coverity scan
