name: Synopsys - Actions

on:
  workflow_dispatch

jobs:
  Polaris:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2        
    - name: Restore
      run: dotnet restore
      
    - name: Polaris Scan
      uses: synopsys-sig/synopsys-action@v1.13.0
      with:
        ### SCANNING: Required fields
        polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_assessment_types: "SCA,SAST"
        ### SCANNING: Optional fields
        polaris_application_name: "FCBR" # github.event.repository.name }}
        polaris_project_name: "WebGoat.Core" # ${{ github.event.repository.name }}
        ### PULL REQUEST COMMENTS: Uncomment below to enable
        # polaris_prComment_enabled: true 
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled
